### ISSUE TITLE
[Centro] Android Developer na Stone Pagamentos

### ISSUE THREAD

**Issue by filpgame** [developersRJ/vagas#1]
<p align="center">
  <img src="http://www.stone.com.br/images/logo-big.png" alt="Stone Logo"/>
</p>

## Descrição da vaga
Se você é dev android, manja dos paranauês das programações em java/kotlin, curte muito tecnologia e adora desafios incríveis, é você quem procuramos!
Abaixo listamos alguns dos conhecimentos que esperamos de você. Ah, esperamos que você também seja uma pessoa bem legal e descontraída. 😄

## Local

[Escritório, Centro - Rio de Janeiro](https://goo.gl/maps/RjDZmvawkyn)

## Benefícios
- Vale refeição/alimentação;
- Vale transporte;
- Plano de saúde;
- Horário flexível;
- Ambiente de trabalho descontraído;
- Snackbar dentro do escritório;
- Entretenimento: Vídeo games, sinuca, mesa de poker, etc;

## Requisitos
**Obrigatórios**
- Experiência com Services e Broadcast no Android;
- Comunicação com APIs / RESTful;
- Conhecimentos sobre o uso de Flavors e Tasks no gradle;
- Git;

**Desejáveis**
- Kotlin;
- Arquitetura MVP;
- Testes Unitários / UI
- Conhecimentos de NDK/JNI;
- Experiência com ProGuard;
- Conhecimento sobre otimização e desempenho

Diferenciais
- Projetos open source

## Nossa empresa
[Nosso Site](http://www.stone.com.br/)
[Blog: Ambiente de Trabalho](http://blog.mundipagg.com/um-ambiente-agradavel-de-trabalho-aumenta-a-produtividade/)

## Contratação
CLT
Presencial
Pleno
Sênior

## Como se candidatar?
Envie um e-mail para devmobile@stone.com.br com seu CV anexado - enviar no assunto: `#MOBILE
[SEU_NOME]`

**Comment by kscastro** [comment]
Sou junior tem algum desafio para ser feito
